openapi: 3.0.0
info:
  title: Shopping Cart API
  version: 1.0.0
  description: APIs to manage a shopping cart

paths:
  /cart/Allproducts:
    post:
      summary: Add all products to the cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cartItemId:
                  type: string
                  format: uuid
                  readOnly: true
      responses:
        '200':
          description: All products added to the cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  cart:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            cartItemId:
                              type: string
                              format: uuid
                            productId:
                              type: string
                              format: uuid
                            quantity:
                              type: integer
                            price:
                              type: number
                            totalPrice:
                              type: number
   
  /dev/cart/getAllCart   :
    get:
      summary: View All product in  cart
      responses:
        '200':
          description: Current products in the shopping cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                              format: uuid
                            cartItemId:
                              type: string
                              format: uuid
                            quantity:
                              type: integer
                            price:
                              type: integer
                            totalPrice:
                              type: integer


  /dev/cart/update/{productId}:
    put:
      summary: Update product in the cart
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Cart product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  cart:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                              format: uuid
                            cartItemId:
                              type: string
                              format: uuid
                            quantity:
                              type: integer
                            price:
                              type: number
                            totalPrice:
                              type: number


    delete:
      summary: Remove product from the cart
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product removed from the cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  cart:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                              format: uuid
                            


  /dev/cart/removeAll  :
    delete:
      summary: Remove all products from the cart
      responses:
        '200':
          description: All products removed from the cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
